const projects = [
  {
    name: "WaveFinder",
    image: "/projects/wavefinder.jpeg",
    description: "message testing using AI and ML",
    link: "https://wavefinder.io",
    year: 2023,
  },
  {
    name: "Alpine Codex",
    image: "/projects/alpine.jpeg",
    description: "intelligent marketing software",
    link: "https://alpine.dev",
    year: 2023,
  },
  {
    name: "Ampry",
    image: "/projects/ampry.jpeg",
    description: "marketing and lead generation",
    link: "https://ampry.com",
    year: 2018,
  },
  {
    name: "autobyte",
    image: "/projects/autobyte.jpeg",
    description: "development-as-a-service platform",
    link: "https://autobyte.dev",
    year: 2023,
  },
  {
    name: "BuilderKit",
    image: "/projects/builderkit.jpeg",
    description: "AI copywriting and content generation assistant",
    link: "https://builderkit.io",
    year: 2023,
  },
  {
    name: "Craft UI",
    image: "/projects/craft.jpeg",
    description: "design system and component library",
    link: "https://craftui.org",
    year: 2023,
  },
  {
    name: "Family History AI",
    image: "/projects/family-history-ai.jpeg",
    description: "enhance and colorize images with AI",
    link: "https://familyhistoryai.com",
    year: 2023,
  },
  {
    name: "Fjord",
    image: "/projects/fjord.jpeg",
    description: "headless next js wordpress starter kit",
    link: "https://fjord.dev",
    year: 2024,
  },
  {
    name: "Lofi Anime",
    image: "/projects/lofi-anime.jpeg",
    description: "generate images in the style of hiroshi nagai",
    link: "https://lofianime.com",
    year: 2023,
  },
  {
    name: "Outr.io",
    image: "/projects/outr.jpeg",
    description: "your AI sales outreach assistant",
    link: "https://outr.io",
    year: 2023,
  },
  {
    name: "Pandium",
    image: "/projects/pandium.jpeg",
    description: "website and product design for pandium.com",
    link: "https://pandium.com",
    year: 2023,
  },
  {
    name: "Presets",
    image: "/projects/presets.jpeg",
    description: "AI powered photo editing software",
    link: "https://presets.com",
    year: 2024,
  },
  {
    name: "Socal Flights",
    image: "/projects/socal-flights.jpeg",
    description: "find best deals on flights from LAX",
    link: "https://socal.flights",
    year: 2021,
  },
  {
    name: "WindPress",
    image: "/projects/windpress.jpeg",
    description: "tailwind and wordpress starter theme",
    link: "https://windpress.wpenginepowered.com",
    year: 2023,
  },
  {
    name: "Zion",
    image: "/projects/zion.jpeg",
    description: "design studio and creative agency",
    link: "https://zion.surf",
    year: 2018,
  },
  {
    name: "bridger.to",
    image: "/projects/bridger.jpeg",
    description: "homepage of bridger tower",
    link: "https://bridger.to",
    year: 1998,
  },
  {
    name: "cameron.so",
    image: "/projects/cameron.jpeg",
    description: "homepage of cameron youngblood",
    link: "https://cameronyoungblood.com",
    year: 1998,
  },
];

export default projects;
